# Generated by Django 5.0.7 on 2025-12-13 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0002_communitymessage"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="musicmatch",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="musicmatch",
            name="user1",
        ),
        migrations.RemoveField(
            model_name="musicmatch",
            name="user2",
        ),
        migrations.DeleteModel(
            name="ListeningParty",
        ),
        migrations.DeleteModel(
            name="MusicMatch",
        ),
    ]
