# Generated by Django 5.0.7 on 2025-12-12 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('focus', 'Focus Mode'), ('workout', 'Working Out'), ('driving', 'Driving'), ('dancing', 'Dancing'), ('singing', 'Sing Along'), ('relaxing', 'Relaxing'), ('party', 'Party')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('min_danceability', models.FloatField(blank=True, null=True)),
                ('max_danceability', models.FloatField(blank=True, null=True)),
                ('min_energy', models.FloatField(blank=True, null=True)),
                ('max_energy', models.FloatField(blank=True, null=True)),
                ('min_valence', models.FloatField(blank=True, null=True)),
                ('max_valence', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shown_at', models.DateTimeField(blank=True, null=True)),
                ('user_action', models.CharField(blank=True, max_length=20)),
                ('mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendations.recommendationmode')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
    ]
